# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pic',
            field=models.ImageField(default=None, upload_to='staff/photo/'),
            preserve_default=False,
        ),
    ]
