# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='pic',
            field=models.ImageField(default=None, upload_to='student/photo/'),
            preserve_default=False,
        ),
    ]
